# Generated by Django 4.1.4 on 2024-07-31 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('authors', models.CharField(db_index=True, max_length=255)),
                ('average_rating', models.FloatField()),
                ('isbn', models.CharField(max_length=255)),
                ('isbn13', models.IntegerField()),
                ('language_code', models.CharField(max_length=100)),
                ('num_pages', models.IntegerField()),
                ('ratings_count', models.IntegerField()),
                ('text_reviews_count', models.IntegerField()),
                ('publication_date', models.DateField()),
                ('publisher', models.TextField(max_length=400)),
            ],
        ),
    ]
